---
- name: supervisord stop
  become: yes
  service:
    name: "{{ supervisord_service_name }}"
    state: stopped
    use: service

- name: supervisord start
  become: yes
  service:
    name: "{{ supervisord_service_name }}"
    state: started
    use: service
  when: supervisord_run_service | default(supervisord_run_service_default)

- name: supervisord restart
  debug: msg="supervisord restart"
  notify:
    - supervisord stop
    - supervisord start

- name: supervisorctl reread
  become: yes
  command: "{{ supervisord_ctlprogram_name }} reread"
  when: supervisord_run_service | default(supervisord_run_service_default)

- name: supervisorctl update
  become: yes
  command: "{{ supervisord_ctlprogram_name }} update"
  when: supervisord_run_service | default(supervisord_run_service_default)
