---
- name: supervisord stop
  sudo: yes
  service: name={{ supervisord_service_name }} state=stopped

- name: supervisord start
  sudo: yes
  service: name={{ supervisord_service_name }} state=started
  when: supervisord_run_service | default(supervisord_run_service_default)

- name: supervisord restart
  debug: msg="supervisord restart"
  notify:
    - supervisord stop
    - supervisord start

- name: supervisorctl reread
  sudo: yes
  command: "{{ supervisord_ctlprogram_name }} reread"
  when: supervisord_run_service | default(supervisord_run_service_default)

- name: supervisorctl update
  sudo: yes
  command: "{{ supervisord_ctlprogram_name }} update"
  when: supervisord_run_service | default(supervisord_run_service_default)
